icons_format = "{icon}"

[theme]
theme = "dracula"
# [theme.overrides]
# idle_bg = "#123456"
# idle_fg = "#abcdef"

[icons]
icons = "material-nf"
[icons.overrides]
backlight = ["󰃚","󰃛","󰃜","󰃝","󰃞","󰃟","󰃠"]
# bat = ["|E|", "|_|", "|=|", "|F|"]
# bat_charging = "|^| "

# Networking Blocks
[[block]]
block = "net"
device = "tun0"
format = " $icon tun0 $speed_down.eng(width:4,p:K,prefix_space:true) "
format_alt = " $icon tun0 $ip $speed_down.eng(width:4,p:K,prefix_space:true) "
inactive_format = ""
missing_format = ""
[block.theme_overrides]
idle_bg = "#81A1C1FF"
idle_fg = "#2E3440"

[[block]]
block = "net"
device = "tailscale0"
format = " $icon tailscale $speed_down.eng(width:4,p:K,prefix_space:true) "
format_alt = " $icon tailscale $ip $speed_down.eng(width:4,p:K,prefix_space:true) "
inactive_format = ""
missing_format = ""
[block.theme_overrides]
idle_bg = "#B48EADFF"
idle_fg = "#2E3440"

[[block]]
block = "net"
device = "wlan0"
format = " $icon $ssid $speed_down.eng(width:4,p:K,prefix_space:true) "
format_alt = " $icon $ssid $ip $speed_down.eng(width:4,p:K,prefix_space:true) "
interval = 5
[block.theme_overrides]
idle_bg = "#81A1C1FF"
idle_fg = "#2E3440"

[[block]]
block = "battery"
driver = "upower"
charging_format = " $icon $percentage "
full_format = " $icon  $percentage "
[block.theme_overrides]
idle_bg = "#8FBCBBFF"
idle_fg = "#2E3440"
good_bg = "#8FBCBBFF"
good_fg = "#2E3440"
warning_bg = "#EBCB8BFF"
warning_fg = "#2E3440"
critical_bg = "#D08770FF"
critical_fg = "#2E3440"

[[block]]
block = "custom"
command = "cccc"
interval = 5
[block.theme_overrides]
idle_bg = "#D08770FF"
idle_fg = "#2E3440"

[[block]]
block = "cpu"
interval = 5
info_cpu = 50
warning_cpu = 75
critical_cpu = 90
format = " $icon $utilization "
[block.theme_overrides]
idle_bg = "#A3BE8CFF"
idle_fg = "#2E3440"
good_bg = "#A3BE8CFF"
good_fg = "#2E3440"
info_bg = "#EBCB8BFF"
info_fg = "#2E3440"
warning_bg = "#D08770FF"
warning_fg = "#2E3440"
critical_bg = "#BF616AFF"
critical_fg = "#ECEFF4"

[[block]]
block = "memory"
#format = " $icon $mem_total_used_percents.eng(w:2) $mem_total_used_percents.bar(w:1,v:true) "
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "
[block.theme_overrides]
idle_bg = "#EBCB8BFF"
idle_fg = "#2E3440"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:2) "
[block.theme_overrides]
idle_bg = "#5E81ACFF"
idle_fg = "#ECEFF4"

[[block]]
block = "sound"
format = " $icon $active_port $volume "
driver = "pulseaudio"
show_volume_when_muted = true
headphones_indicator = true
[block.active_port_mappings]
"analog-output-speaker" = "laptop-speakers"
[[block.click]]
button = "left"
cmd = "pactl set-sink-mute @DEFAULT_SINK@ toggle"
[block.theme_overrides]
idle_bg = "#8FBCBBFF"
idle_fg = "#2E3440"
warning_bg = "#BF616AFF"
warning_fg = "#ECEFF4"

[[block]]
block = "backlight"
format = " $icon  $brightness "
root_scaling = 1
[[block.click]]
button = "left"
cmd = ""
[block.theme_overrides]
idle_bg = "#EBCB8BFF"
idle_fg = "#2E3440"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
[block.theme_overrides]
idle_bg = "#4C566AFF"
idle_fg = "#D8DEE9"
