icons_format = "{icon}"

[theme]
theme = "dracula"
# [theme.overrides]
# idle_bg = "#123456"
# idle_fg = "#abcdef"

[icons]
icons = "awesome5"
# [icons.overrides]
# bat = ["|E|", "|_|", "|=|", "|F|"]
# bat_charging = "|^| "

# Networking Blocks
[[block]]
block = "net"
device = "tun0"
format = " $device: $speed_down.eng(width:4,p:K,prefix_space:true) " 
inactive_format = ""
missing_format = ""
[block.theme_overrides]
idle_bg = "#223456DD"

[[block]]
block = "net"
device = "tailscale0"
format = " $device: $speed_down.eng(width:4,p:K,prefix_space:true) " 
inactive_format = ""
missing_format = ""
[block.theme_overrides]
idle_bg = "#523456DD"

[[block]]
block = "net"
device = "wlan0"
format = " ^icon_net_wireless $ssid $ip $speed_down.eng(width:4,p:K,prefix_space:true) " 
interval = 5
[block.theme_overrides]
idle_bg = "#123456DD"

[[block]]
block = "battery"
driver = "upower"
charging_format = " $icon $percentage "
full_format = " $icon  $percentage "
[block.theme_overrides]
idle_bg = "#128934DD"

[[block]]
block = "cpu"
interval = 5
info_cpu = 30
warning_cpu = 60
critical_cpu = 90
format = " $icon $utilization $barchart"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) $mem_total_used_percents.bar(w:1,v:true) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
